### ISSUE TITLE
Replace try-catch with raise_for_status

### ISSUE THREAD

**Issue by luandy64** [Kalai-Wavicle/tap-square#1]
https://github.com/Kalai-Wavicle/tap-square/blob/736cfa03947695d890d8907d9fbf36849e2b1375/tap-square/__init__.py#L121-L127

This can all be replaced with a call to `raise_for_status()` before the `.json()` call:

```python
def get_data(some_url):
    response = requests.get(some_url)
    response.raise_for_status() # Handles 4XX- 5XX status codes
    return response.json()
```

**Comment by Kalai-Wavicle** [comment]
Updated the code for try catch, also added below new list of square APIs in tap-square.

list_payments
retrieve_payment
list_refunds
retrieve_refund
orders
devices_codes
retrieve_device_code
terminals_checkouts
retrieve_terminal_checkout
list_disputes
retrieve_disputes

**Comment by luandy64** [comment]
@Kalai-Wavicle Does that mean you think this issue can be closed now?

**Comment by Kalai-Wavicle** [comment]
@luandy64 Yes, we can close this issue.
